services:
  app:
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    image: test
    environment:
      DB_URL: ${DB_URL}
      DB: ${DB}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
  db:
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5431:5432"
    image: postgres:alpine